// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RepositoryLayer;

#nullable disable

namespace RepositoryLayer.Migrations
{
    [DbContext(typeof(PawFundContext))]
    [Migration("20241001062137_v2")]
    partial class v2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CertificationUser", b =>
                {
                    b.Property<int>("CertificationsId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("CertificationsId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("CertificationUser");
                });

            modelBuilder.Entity("Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool?>("Status")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "ShelterStaff"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Donor"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Volunteer"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Adopter"
                        });
                });

            modelBuilder.Entity("ModelLayer.Entities.AdoptionRegistrationForm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AdopterId")
                        .HasColumnType("int");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("IdentityProof")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("IncomeAmount")
                        .HasColumnType("decimal(16, 4)");

                    b.Property<int>("PetId")
                        .HasColumnType("int");

                    b.Property<int>("ShelterStaffId")
                        .HasColumnType("int");

                    b.Property<bool?>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PetId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("AdoptionRegistrationForm");
                });

            modelBuilder.Entity("ModelLayer.Entities.Certification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Desciption")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PetId")
                        .HasColumnType("int");

                    b.Property<int>("ShelterStaffId")
                        .HasColumnType("int");

                    b.Property<bool?>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PetId")
                        .IsUnique();

                    b.ToTable("Certification");
                });

            modelBuilder.Entity("ModelLayer.Entities.Donation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(16, 4)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DonorId")
                        .HasColumnType("int");

                    b.Property<int>("ShelterId")
                        .HasColumnType("int");

                    b.Property<bool?>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ShelterId");

                    b.HasIndex("UserId");

                    b.ToTable("Donations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 100000m,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DonorId = 6,
                            ShelterId = 1
                        },
                        new
                        {
                            Id = 2,
                            Amount = 200000m,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DonorId = 7,
                            ShelterId = 1
                        },
                        new
                        {
                            Id = 3,
                            Amount = 543333m,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DonorId = 8,
                            ShelterId = 2
                        },
                        new
                        {
                            Id = 4,
                            Amount = 632229m,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DonorId = 9,
                            ShelterId = 2
                        },
                        new
                        {
                            Id = 5,
                            Amount = 760000m,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DonorId = 7,
                            ShelterId = 1
                        });
                });

            modelBuilder.Entity("ModelLayer.Entities.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ShelterId")
                        .HasColumnType("int");

                    b.Property<bool?>("Status")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("ShelterId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("ModelLayer.Entities.EventUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<bool?>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("EventUser");
                });

            modelBuilder.Entity("ModelLayer.Entities.FeedBack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<bool?>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("FeedBacks");
                });

            modelBuilder.Entity("ModelLayer.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool?>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("ModelLayer.Entities.Pet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdoptionStatus")
                        .HasColumnType("longtext");

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Breed")
                        .HasColumnType("longtext");

                    b.Property<string>("Color")
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Gender")
                        .HasColumnType("longtext");

                    b.Property<string>("Image")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ShelterID")
                        .HasColumnType("int");

                    b.Property<string>("Size")
                        .HasColumnType("longtext");

                    b.Property<bool?>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("StatusId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ShelterID");

                    b.HasIndex("UserID");

                    b.ToTable("Pets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Buddy",
                            ShelterID = 1,
                            Type = "Dog",
                            UserID = 17
                        },
                        new
                        {
                            Id = 2,
                            Name = "Whiskers",
                            ShelterID = 1,
                            Type = "Cat",
                            UserID = 17
                        },
                        new
                        {
                            Id = 3,
                            Name = "Max",
                            ShelterID = 1,
                            Type = "Dog",
                            UserID = 16
                        },
                        new
                        {
                            Id = 4,
                            Name = "Luna",
                            ShelterID = 1,
                            Type = "Cat",
                            UserID = 14
                        },
                        new
                        {
                            Id = 5,
                            Name = "Bella",
                            ShelterID = 1,
                            Type = "Dog"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Lux",
                            ShelterID = 1,
                            Type = "Cat"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Dono",
                            ShelterID = 1,
                            Type = "Dog"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Linker",
                            ShelterID = 1,
                            Type = "Cat"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Dawin",
                            ShelterID = 1,
                            Type = "Dog",
                            UserID = 15
                        },
                        new
                        {
                            Id = 10,
                            Name = "Modor",
                            ShelterID = 2,
                            Type = "Cat"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Pingking",
                            ShelterID = 2,
                            Type = "Dog"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Seto",
                            ShelterID = 2,
                            Type = "Cat"
                        },
                        new
                        {
                            Id = 13,
                            Name = "kaiba",
                            ShelterID = 2,
                            Type = "Dog"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Asuka",
                            ShelterID = 2,
                            Type = "Cat"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Jax",
                            ShelterID = 2,
                            Type = "Dog"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Jihn",
                            ShelterID = 2,
                            Type = "Cat"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Kaisa",
                            ShelterID = 2,
                            Type = "Dog"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Bump",
                            ShelterID = 2,
                            Type = "Dog"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Rasko",
                            ShelterID = 2,
                            Type = "Dog"
                        });
                });

            modelBuilder.Entity("ModelLayer.Entities.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PetId")
                        .HasColumnType("int");

                    b.Property<bool?>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PetId");

                    b.HasIndex("UserId");

                    b.ToTable("Post");
                });

            modelBuilder.Entity("ModelLayer.Entities.Shelter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capaxity")
                        .HasColumnType("int");

                    b.Property<decimal?>("DonationAmount")
                        .HasColumnType("decimal(16, 4)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool?>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Website")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Shelters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capaxity = 20,
                            Email = "PetShelter1@email.com",
                            Location = "Tp. HCM",
                            Name = "Shelter1",
                            PhoneNumber = "1234567890"
                        },
                        new
                        {
                            Id = 2,
                            Capaxity = 20,
                            Email = "PetShelter2@email.com",
                            Location = "Ha Noi",
                            Name = "Shelter2",
                            PhoneNumber = "0987654321"
                        });
                });

            modelBuilder.Entity("ModelLayer.Entities.ShelterStaff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ShelterId")
                        .HasColumnType("int");

                    b.Property<bool?>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ShelterId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("ShelterStaffs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ShelterId = 1,
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            ShelterId = 1,
                            UserId = 3
                        },
                        new
                        {
                            Id = 3,
                            ShelterId = 2,
                            UserId = 4
                        },
                        new
                        {
                            Id = 4,
                            ShelterId = 2,
                            UserId = 5
                        });
                });

            modelBuilder.Entity("ModelLayer.Entities.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Disease")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PetId")
                        .HasColumnType("int");

                    b.Property<bool?>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Vaccine")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("PetId");

                    b.ToTable("Statuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Disease = "Parvovirus Infection",
                            Name = "Canine Parvovirus",
                            PetId = 1,
                            Vaccine = "Parvovirus Vaccine"
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2024, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Disease = "Distemper Virus",
                            Name = "Canine Distemper",
                            PetId = 3,
                            Vaccine = "Distemper Vaccine"
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Disease = "Rabies Virus",
                            Name = "Rabies",
                            PetId = 5,
                            Vaccine = "Rabies Vaccine"
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Disease = "FeLV",
                            Name = "Feline Leukemia Virus",
                            PetId = 2,
                            Vaccine = "FeLV Vaccine"
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateTime(2024, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Disease = "FIV",
                            Name = "Feline Immunodeficiency Virus",
                            PetId = 4,
                            Vaccine = "None"
                        });
                });

            modelBuilder.Entity("ModelLayer.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Image")
                        .HasColumnType("longtext");

                    b.Property<string>("Location")
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .HasColumnType("longtext");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int");

                    b.Property<bool?>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Token")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("TotalDonation")
                        .HasColumnType("decimal(16, 4)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "Admin@email.com",
                            Password = "$2a$11$DVFcE.CrjVUZZ26AMtfJs.oYXsKYPGR4CuLFtR9.HrJ.Vn0saV822",
                            Username = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Email = "Staff1@email.com",
                            Password = "$2a$11$h7X75u2KLDplfuq8MrDzJuZRjrQuqTfWZb.8akAUyiuHoaNsUAbUS",
                            Username = "Staff1"
                        },
                        new
                        {
                            Id = 3,
                            Email = "Staff2@email.com",
                            Password = "$2a$11$8owZyZ9TWM2wepY1ZyBLq.DlGCrOjxYq.B1ED9iTooO94F4SgGBR.",
                            Username = "Staff2"
                        },
                        new
                        {
                            Id = 4,
                            Email = "Staff3@email.com",
                            Password = "$2a$11$s038o3LCToFyBfJxq0sl3.Dvlll5f0vBOVw.9DcpKAl5iowEy7Doi",
                            Username = "Staff3"
                        },
                        new
                        {
                            Id = 5,
                            Email = "Staff4@email.com",
                            Password = "$2a$11$qhOAtA1oySjDS8rSOkHDre/tePtKD59357vEmJS9u89GGZwCNw38m",
                            Username = "Staff4"
                        },
                        new
                        {
                            Id = 6,
                            Email = "Donor1@email.com",
                            Password = "$2a$11$5FhXhU4kx6xPD5gnoWtvu.pNcJ1PaE5MabG208hS7nhgAMJolorlq",
                            Username = "Donor1"
                        },
                        new
                        {
                            Id = 7,
                            Email = "Donor2@email.com",
                            Password = "$2a$11$upyXLWl9wkaRTdsOi9KutOjm78Vs7TxDtO63nc7OHmLh1/4e17L06",
                            Username = "Donor2"
                        },
                        new
                        {
                            Id = 8,
                            Email = "Donor3@email.com",
                            Password = "$2a$11$xMGVdiVsIT6V7LlKMyF/i.aw78dGVH7/VdLcMSSrsw2/ojsmNzGCG",
                            Username = "Donor3"
                        },
                        new
                        {
                            Id = 9,
                            Email = "Donor4@email.com",
                            Password = "$2a$11$RSgoozh82WBjQi5RmRhF8u01QnBvKaMJ3Ma8rW3eN.lGnuag7tjiO",
                            Username = "Donor4"
                        },
                        new
                        {
                            Id = 10,
                            Email = "Volunteer1@email.com",
                            Password = "$2a$11$rCtOz5uhvFDc/8M7x0tbyuo3qZKPPapSJyMoVS1P5nh4gmW8OHRxO",
                            Username = "Volunteer1"
                        },
                        new
                        {
                            Id = 11,
                            Email = "Volunteer2@email.com",
                            Password = "$2a$11$lAt9Bde3wHCHWxNIm1iwlOjX8g0KxCipjz.CUXgDm6Z0mTNEvRgse",
                            Username = "Volunteer2"
                        },
                        new
                        {
                            Id = 12,
                            Email = "Volunteer3@email.com",
                            Password = "$2a$11$grM7vZLtcS3QmlA1./2WveZTn3vobukqgFFMvmfpjO.dXMBnTDsxW",
                            Username = "Volunteer3"
                        },
                        new
                        {
                            Id = 13,
                            Email = "Volunteer4@email.com",
                            Password = "$2a$11$En3NF1rj0f9TcFjKWV07Xu9NJaONmoaD0VrxnwadAwqiI4y7ZqBRy",
                            Username = "Volunteer4"
                        },
                        new
                        {
                            Id = 14,
                            Email = "Adopter1@email.com",
                            Password = "$2a$11$SXtVEtX0urACeQ8692TA4ug2yM3gOyVKveKdyCvBMQzQjcWPwTyN2",
                            Username = "Adopter1"
                        },
                        new
                        {
                            Id = 15,
                            Email = "Adopter2@email.com",
                            Password = "$2a$11$9au2iFFvy.Y8B274IdF3DO6/jGXI1m7h3Sgb8epYJyVJhheMtw5Z.",
                            Username = "Adopter2"
                        },
                        new
                        {
                            Id = 16,
                            Email = "Adopter3@email.com",
                            Password = "$2a$11$c5UGpxurk.g3dqTRPxkRcu8yrywFnsQa1hpX2QTRC188pwNuUWxge",
                            Username = "Adopter3"
                        },
                        new
                        {
                            Id = 17,
                            Email = "Adopter4@email.com",
                            Password = "$2a$11$mP3Ir1qeoDbVKAOvNAD4TekXEgwETSBlbY3JBZkFP3aDec8DkEg9O",
                            Username = "Adopter4"
                        });
                });

            modelBuilder.Entity("ModelLayer.Entities.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<bool?>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRole");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RoleId = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            RoleId = 2,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            RoleId = 2,
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            RoleId = 2,
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            RoleId = 2,
                            UserId = 5
                        },
                        new
                        {
                            Id = 6,
                            RoleId = 3,
                            UserId = 6
                        },
                        new
                        {
                            Id = 7,
                            RoleId = 3,
                            UserId = 7
                        },
                        new
                        {
                            Id = 8,
                            RoleId = 3,
                            UserId = 8
                        },
                        new
                        {
                            Id = 9,
                            RoleId = 3,
                            UserId = 9
                        },
                        new
                        {
                            Id = 10,
                            RoleId = 4,
                            UserId = 10
                        },
                        new
                        {
                            Id = 11,
                            RoleId = 4,
                            UserId = 11
                        },
                        new
                        {
                            Id = 12,
                            RoleId = 4,
                            UserId = 12
                        },
                        new
                        {
                            Id = 13,
                            RoleId = 4,
                            UserId = 13
                        },
                        new
                        {
                            Id = 14,
                            RoleId = 5,
                            UserId = 14
                        },
                        new
                        {
                            Id = 15,
                            RoleId = 5,
                            UserId = 15
                        },
                        new
                        {
                            Id = 16,
                            RoleId = 5,
                            UserId = 16
                        },
                        new
                        {
                            Id = 17,
                            RoleId = 5,
                            UserId = 17
                        });
                });

            modelBuilder.Entity("CertificationUser", b =>
                {
                    b.HasOne("ModelLayer.Entities.Certification", null)
                        .WithMany()
                        .HasForeignKey("CertificationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModelLayer.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ModelLayer.Entities.AdoptionRegistrationForm", b =>
                {
                    b.HasOne("ModelLayer.Entities.Pet", "Pet")
                        .WithOne("AdoptionRegistrationForm")
                        .HasForeignKey("ModelLayer.Entities.AdoptionRegistrationForm", "PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModelLayer.Entities.User", "User")
                        .WithMany("AdoptionRegistrationForms")
                        .HasForeignKey("UserId");

                    b.Navigation("Pet");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ModelLayer.Entities.Certification", b =>
                {
                    b.HasOne("ModelLayer.Entities.Pet", "Pet")
                        .WithOne("Certification")
                        .HasForeignKey("ModelLayer.Entities.Certification", "PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pet");
                });

            modelBuilder.Entity("ModelLayer.Entities.Donation", b =>
                {
                    b.HasOne("ModelLayer.Entities.Shelter", "Shelter")
                        .WithMany("Donations")
                        .HasForeignKey("ShelterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModelLayer.Entities.User", "User")
                        .WithMany("Donations")
                        .HasForeignKey("UserId");

                    b.Navigation("Shelter");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ModelLayer.Entities.Event", b =>
                {
                    b.HasOne("ModelLayer.Entities.Shelter", "Shelter")
                        .WithMany("Events")
                        .HasForeignKey("ShelterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shelter");
                });

            modelBuilder.Entity("ModelLayer.Entities.EventUser", b =>
                {
                    b.HasOne("ModelLayer.Entities.Event", "Event")
                        .WithMany("EventUser")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModelLayer.Entities.User", "User")
                        .WithOne("EventUser")
                        .HasForeignKey("ModelLayer.Entities.EventUser", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ModelLayer.Entities.FeedBack", b =>
                {
                    b.HasOne("ModelLayer.Entities.Post", "Post")
                        .WithMany("FeedBacks")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModelLayer.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ModelLayer.Entities.Notification", b =>
                {
                    b.HasOne("ModelLayer.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ModelLayer.Entities.Pet", b =>
                {
                    b.HasOne("ModelLayer.Entities.Shelter", "Shelter")
                        .WithMany("Pets")
                        .HasForeignKey("ShelterID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModelLayer.Entities.User", "User")
                        .WithMany("Pets")
                        .HasForeignKey("UserID");

                    b.Navigation("Shelter");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ModelLayer.Entities.Post", b =>
                {
                    b.HasOne("ModelLayer.Entities.Pet", "Pet")
                        .WithMany()
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModelLayer.Entities.User", "User")
                        .WithMany("Posts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pet");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ModelLayer.Entities.ShelterStaff", b =>
                {
                    b.HasOne("ModelLayer.Entities.Shelter", "Shelter")
                        .WithMany("Staffs")
                        .HasForeignKey("ShelterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModelLayer.Entities.User", "Users")
                        .WithOne("ShelterStaff")
                        .HasForeignKey("ModelLayer.Entities.ShelterStaff", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shelter");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("ModelLayer.Entities.Status", b =>
                {
                    b.HasOne("ModelLayer.Entities.Pet", "Pet")
                        .WithMany("Statuses")
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pet");
                });

            modelBuilder.Entity("ModelLayer.Entities.User", b =>
                {
                    b.HasOne("Domain.Entities.Role", null)
                        .WithMany("Users")
                        .HasForeignKey("RoleId");
                });

            modelBuilder.Entity("ModelLayer.Entities.UserRole", b =>
                {
                    b.HasOne("Domain.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModelLayer.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("ModelLayer.Entities.Event", b =>
                {
                    b.Navigation("EventUser");
                });

            modelBuilder.Entity("ModelLayer.Entities.Pet", b =>
                {
                    b.Navigation("AdoptionRegistrationForm");

                    b.Navigation("Certification");

                    b.Navigation("Statuses");
                });

            modelBuilder.Entity("ModelLayer.Entities.Post", b =>
                {
                    b.Navigation("FeedBacks");
                });

            modelBuilder.Entity("ModelLayer.Entities.Shelter", b =>
                {
                    b.Navigation("Donations");

                    b.Navigation("Events");

                    b.Navigation("Pets");

                    b.Navigation("Staffs");
                });

            modelBuilder.Entity("ModelLayer.Entities.User", b =>
                {
                    b.Navigation("AdoptionRegistrationForms");

                    b.Navigation("Donations");

                    b.Navigation("EventUser");

                    b.Navigation("Notifications");

                    b.Navigation("Pets");

                    b.Navigation("Posts");

                    b.Navigation("ShelterStaff");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
