// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RepositoryLayer;

#nullable disable

namespace RepositoryLayer.Migrations
{
    [DbContext(typeof(PawFundContext))]
    [Migration("20241012033229_v5")]
    partial class v5
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("IsDelete")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "ShelterStaff"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Donor"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Volunteer"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Adopter"
                        });
                });

            modelBuilder.Entity("ModelLayer.Entities.AdoptionRegistrationForm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AdopterId")
                        .HasColumnType("int");

                    b.Property<string>("IdentificationImage")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("IdentificationImageBackSide")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("IncomeAmount")
                        .HasColumnType("decimal(16, 4)");

                    b.Property<bool?>("IsDelete")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("PetId")
                        .HasColumnType("int");

                    b.Property<int?>("ShelterStaffId")
                        .HasColumnType("int");

                    b.Property<string>("SocialAccount")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool?>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PetId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Forms");
                });

            modelBuilder.Entity("ModelLayer.Entities.Certification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Desciption")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool?>("IsDelete")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("PetId")
                        .HasColumnType("int");

                    b.Property<int>("ShelterStaffId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PetId")
                        .IsUnique();

                    b.HasIndex("ShelterStaffId");

                    b.HasIndex("UserId");

                    b.ToTable("Certifications");
                });

            modelBuilder.Entity("ModelLayer.Entities.Donation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(16, 4)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DonorId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsDelete")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("ShelterId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DonorId");

                    b.HasIndex("ShelterId");

                    b.ToTable("Donations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 100000m,
                            Date = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DonorId = 6,
                            ShelterId = 1
                        },
                        new
                        {
                            Id = 2,
                            Amount = 200000m,
                            Date = new DateTime(2024, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DonorId = 7,
                            ShelterId = 1
                        },
                        new
                        {
                            Id = 3,
                            Amount = 543333m,
                            Date = new DateTime(2024, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DonorId = 8,
                            ShelterId = 2
                        },
                        new
                        {
                            Id = 4,
                            Amount = 632229m,
                            Date = new DateTime(2024, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DonorId = 9,
                            ShelterId = 2
                        },
                        new
                        {
                            Id = 5,
                            Amount = 760000m,
                            Date = new DateTime(2024, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DonorId = 7,
                            ShelterId = 2
                        });
                });

            modelBuilder.Entity("ModelLayer.Entities.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool?>("IsDelete")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ShelterId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ShelterId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("ModelLayer.Entities.FeedBack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool?>("IsDelete")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("FeedBacks");
                });

            modelBuilder.Entity("ModelLayer.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<bool?>("IsDelete")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("ModelLayer.Entities.Pet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdoptionStatus")
                        .HasColumnType("longtext");

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Breed")
                        .HasColumnType("longtext");

                    b.Property<string>("Color")
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Gender")
                        .HasColumnType("longtext");

                    b.Property<string>("Image")
                        .HasColumnType("longtext");

                    b.Property<bool?>("IsDelete")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ShelterID")
                        .HasColumnType("int");

                    b.Property<string>("Size")
                        .HasColumnType("longtext");

                    b.Property<int?>("StatusId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ShelterID");

                    b.HasIndex("UserID");

                    b.ToTable("Pets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AdoptionStatus = "Adopted",
                            Image = "https://storage.googleapis.com/pawfund-e7fdd.appspot.com/5b4c37c7-7668-4af4-af72-4dcb2ab75047.png",
                            Name = "Buddy",
                            ShelterID = 1,
                            Type = "Dog",
                            UserID = 17
                        },
                        new
                        {
                            Id = 2,
                            AdoptionStatus = "Available",
                            Image = "https://storage.googleapis.com/pawfund-e7fdd.appspot.com/5b4c37c7-7668-4af4-af72-4dcb2ab75047.png",
                            Name = "Whiskers",
                            ShelterID = 1,
                            Type = "Cat"
                        },
                        new
                        {
                            Id = 3,
                            AdoptionStatus = "Adopted",
                            Image = "https://storage.googleapis.com/pawfund-e7fdd.appspot.com/5b4c37c7-7668-4af4-af72-4dcb2ab75047.png",
                            Name = "Max",
                            ShelterID = 1,
                            Type = "Dog",
                            UserID = 16
                        },
                        new
                        {
                            Id = 4,
                            AdoptionStatus = "Adopted",
                            Image = "https://storage.googleapis.com/pawfund-e7fdd.appspot.com/5b4c37c7-7668-4af4-af72-4dcb2ab75047.png",
                            Name = "Luna",
                            ShelterID = 1,
                            Type = "Cat",
                            UserID = 14
                        },
                        new
                        {
                            Id = 5,
                            AdoptionStatus = "Available",
                            Image = "https://storage.googleapis.com/pawfund-e7fdd.appspot.com/5b4c37c7-7668-4af4-af72-4dcb2ab75047.png",
                            Name = "Bella",
                            ShelterID = 1,
                            Type = "Dog"
                        },
                        new
                        {
                            Id = 6,
                            AdoptionStatus = "Available",
                            Image = "https://storage.googleapis.com/pawfund-e7fdd.appspot.com/5b4c37c7-7668-4af4-af72-4dcb2ab75047.png",
                            Name = "Lux",
                            ShelterID = 1,
                            Type = "Cat"
                        },
                        new
                        {
                            Id = 7,
                            AdoptionStatus = "Available",
                            Image = "https://storage.googleapis.com/pawfund-e7fdd.appspot.com/5b4c37c7-7668-4af4-af72-4dcb2ab75047.png",
                            Name = "Dono",
                            ShelterID = 1,
                            Type = "Dog"
                        },
                        new
                        {
                            Id = 8,
                            AdoptionStatus = "Available",
                            Image = "https://storage.googleapis.com/pawfund-e7fdd.appspot.com/5b4c37c7-7668-4af4-af72-4dcb2ab75047.png",
                            Name = "Linker",
                            ShelterID = 1,
                            Type = "Cat"
                        },
                        new
                        {
                            Id = 9,
                            AdoptionStatus = "Adopted",
                            Image = "https://storage.googleapis.com/pawfund-e7fdd.appspot.com/5b4c37c7-7668-4af4-af72-4dcb2ab75047.png",
                            Name = "Dawin",
                            ShelterID = 1,
                            Type = "Dog",
                            UserID = 15
                        },
                        new
                        {
                            Id = 10,
                            AdoptionStatus = "Available",
                            Image = "https://storage.googleapis.com/pawfund-e7fdd.appspot.com/5b4c37c7-7668-4af4-af72-4dcb2ab75047.png",
                            Name = "Modor",
                            ShelterID = 2,
                            Type = "Cat"
                        },
                        new
                        {
                            Id = 11,
                            AdoptionStatus = "Available",
                            Image = "https://storage.googleapis.com/pawfund-e7fdd.appspot.com/5b4c37c7-7668-4af4-af72-4dcb2ab75047.png",
                            Name = "Pingking",
                            ShelterID = 2,
                            Type = "Dog"
                        },
                        new
                        {
                            Id = 12,
                            AdoptionStatus = "Available",
                            Image = "https://storage.googleapis.com/pawfund-e7fdd.appspot.com/5b4c37c7-7668-4af4-af72-4dcb2ab75047.png",
                            Name = "Seto",
                            ShelterID = 2,
                            Type = "Cat"
                        },
                        new
                        {
                            Id = 13,
                            AdoptionStatus = "Available",
                            Image = "https://storage.googleapis.com/pawfund-e7fdd.appspot.com/5b4c37c7-7668-4af4-af72-4dcb2ab75047.png",
                            Name = "kaiba",
                            ShelterID = 2,
                            Type = "Dog"
                        },
                        new
                        {
                            Id = 14,
                            AdoptionStatus = "Available",
                            Image = "https://storage.googleapis.com/pawfund-e7fdd.appspot.com/5b4c37c7-7668-4af4-af72-4dcb2ab75047.png",
                            Name = "Asuka",
                            ShelterID = 2,
                            Type = "Cat"
                        },
                        new
                        {
                            Id = 15,
                            AdoptionStatus = "Available",
                            Image = "https://storage.googleapis.com/pawfund-e7fdd.appspot.com/5b4c37c7-7668-4af4-af72-4dcb2ab75047.png",
                            Name = "Jax",
                            ShelterID = 2,
                            Type = "Dog"
                        },
                        new
                        {
                            Id = 16,
                            AdoptionStatus = "Available",
                            Image = "https://storage.googleapis.com/pawfund-e7fdd.appspot.com/5b4c37c7-7668-4af4-af72-4dcb2ab75047.png",
                            Name = "Jihn",
                            ShelterID = 2,
                            Type = "Cat"
                        },
                        new
                        {
                            Id = 18,
                            AdoptionStatus = "Available",
                            Image = "https://storage.googleapis.com/pawfund-e7fdd.appspot.com/5b4c37c7-7668-4af4-af72-4dcb2ab75047.png",
                            Name = "Kaisa",
                            ShelterID = 2,
                            Type = "Dog"
                        },
                        new
                        {
                            Id = 19,
                            AdoptionStatus = "Available",
                            Image = "https://storage.googleapis.com/pawfund-e7fdd.appspot.com/5b4c37c7-7668-4af4-af72-4dcb2ab75047.png",
                            Name = "Bump",
                            ShelterID = 2,
                            Type = "Dog"
                        },
                        new
                        {
                            Id = 20,
                            AdoptionStatus = "Available",
                            Image = "https://storage.googleapis.com/pawfund-e7fdd.appspot.com/5b4c37c7-7668-4af4-af72-4dcb2ab75047.png",
                            Name = "Rasko",
                            ShelterID = 2,
                            Type = "Dog"
                        });
                });

            modelBuilder.Entity("ModelLayer.Entities.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool?>("IsDelete")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("PetId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PetId");

                    b.HasIndex("UserId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("ModelLayer.Entities.Shelter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capaxity")
                        .HasColumnType("int");

                    b.Property<decimal?>("DonationAmount")
                        .HasColumnType("decimal(16, 4)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool?>("IsDelete")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Website")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Shelters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capaxity = 20,
                            Email = "PetShelter1@email.com",
                            Location = "Tp. HCM",
                            Name = "Shelter1",
                            PhoneNumber = "1234567890"
                        },
                        new
                        {
                            Id = 2,
                            Capaxity = 20,
                            Email = "PetShelter2@email.com",
                            Location = "Ha Noi",
                            Name = "Shelter2",
                            PhoneNumber = "0987654321"
                        });
                });

            modelBuilder.Entity("ModelLayer.Entities.SmsMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("From")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool?>("IsDelete")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("To")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("SmsMessages");
                });

            modelBuilder.Entity("ModelLayer.Entities.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Disease")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool?>("IsDelete")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("PetId")
                        .HasColumnType("int");

                    b.Property<string>("Vaccine")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("PetId");

                    b.ToTable("Statuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Disease = "Parvovirus Infection",
                            PetId = 1,
                            Vaccine = "Parvovirus Vaccine"
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2024, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Disease = "Distemper Virus",
                            PetId = 3,
                            Vaccine = "Distemper Vaccine"
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Disease = "Rabies Virus",
                            PetId = 5,
                            Vaccine = "Rabies Vaccine"
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Disease = "FeLV",
                            PetId = 2,
                            Vaccine = "FeLV Vaccine"
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateTime(2024, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Disease = "FIV",
                            PetId = 4,
                            Vaccine = "None"
                        });
                });

            modelBuilder.Entity("ModelLayer.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("EventId")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .HasColumnType("longtext");

                    b.Property<bool?>("IsDelete")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Location")
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .HasColumnType("longtext");

                    b.Property<int?>("ShelterId")
                        .HasColumnType("int");

                    b.Property<bool?>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Token")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("TotalDonation")
                        .HasColumnType("decimal(16, 4)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("EventId");

                    b.HasIndex("ShelterId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "Admin@email.com",
                            Password = "$2a$11$FHTXJux6f/KCYKtuI4ajB.6hLmBOFJuPhpBFoCwysumge7A7AbMwq",
                            Username = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Email = "Staff1@email.com",
                            Password = "$2a$11$HeEQrfeXNP.9lBVhcBf3BuyPxonsJLElgTydxvnE4CQH7X0tB0vd6",
                            ShelterId = 1,
                            Username = "Staff1"
                        },
                        new
                        {
                            Id = 3,
                            Email = "Staff2@email.com",
                            Password = "$2a$11$OWrjdR43MpZsF54NnNkO1.5EutiX4Z/jofoP8nLSEfuJnfICNfMpa",
                            ShelterId = 1,
                            Username = "Staff2"
                        },
                        new
                        {
                            Id = 4,
                            Email = "Staff3@email.com",
                            Password = "$2a$11$tSCbSDha38jp9653w/ypQOR1.cKIafncircF9PUK/YvBUxzERAJNG",
                            ShelterId = 2,
                            Username = "Staff3"
                        },
                        new
                        {
                            Id = 5,
                            Email = "Staff4@email.com",
                            Password = "$2a$11$OzOUvIKzN6qlJaszjLp05ulIUrkj162.KrvaXWTi1jpgPkkIdQ2zi",
                            ShelterId = 2,
                            Username = "Staff4"
                        },
                        new
                        {
                            Id = 6,
                            Email = "Donor1@email.com",
                            Image = "https://storage.googleapis.com/pawfund-e7fdd.appspot.com/5b4c37c7-7668-4af4-af72-4dcb2ab75047.png",
                            Location = "HCM",
                            Password = "$2a$11$u5j4zSMtKtW5YZeUBraJpuY1weyk3FRAtl37fUaIHOKA6lkrWN5l6",
                            Phone = "123456789",
                            Username = "Donor1"
                        },
                        new
                        {
                            Id = 7,
                            Email = "Donor2@email.com",
                            Password = "$2a$11$aqSKrl8FQ5wMfdePQrLFw.8MDY7AHR/EiFnz6oQ2qk9LaE.L0S15y",
                            Username = "Donor2"
                        },
                        new
                        {
                            Id = 8,
                            Email = "Donor3@email.com",
                            Password = "$2a$11$v6mmWRtuQp6bTnv0tOuche4pNZVkA4vAKyUzNyiVzkm29qzRXgs9m",
                            Username = "Donor3"
                        },
                        new
                        {
                            Id = 9,
                            Email = "Donor4@email.com",
                            Password = "$2a$11$z1w6Bd6rF/3jEFEmSRl6PupVaey6iZAYglkeVbk1hH.EctjX1PnwK",
                            Username = "Donor4"
                        },
                        new
                        {
                            Id = 10,
                            Email = "Volunteer1@email.com",
                            Password = "$2a$11$PtA91N3TxNi4CCl62KwZ3OOmovena4xd8/Bq.f0teM3rxQPgbbRyu",
                            Username = "Volunteer1"
                        },
                        new
                        {
                            Id = 11,
                            Email = "Volunteer2@email.com",
                            Password = "$2a$11$iZbfBW6RY.f/d6VH4x9F3.ZtmGAboT7bOE1.h59sCegYMM6Zx1RfW",
                            Username = "Volunteer2"
                        },
                        new
                        {
                            Id = 12,
                            Email = "Volunteer3@email.com",
                            Password = "$2a$11$tnZ3esO7UVbRIO3H5qflrOZuHOvCyXF65FCrCBogsA6Gi4/huB2C.",
                            Username = "Volunteer3"
                        },
                        new
                        {
                            Id = 13,
                            Email = "Volunteer4@email.com",
                            Password = "$2a$11$5v3KY7Uvd/CFtegDzkgSZ.3mHUpJsjIejxR9vgQRBHu8DspCooXcO",
                            Username = "Volunteer4"
                        },
                        new
                        {
                            Id = 14,
                            Email = "Adopter1@email.com",
                            Password = "$2a$11$g4OzqCrKfTu.gk9ny47RlOH0UFAA3mNMCVkv/KDD4/CkgetUDxxNe",
                            Username = "Adopter1"
                        },
                        new
                        {
                            Id = 15,
                            Email = "Adopter2@email.com",
                            Password = "$2a$11$8toMTQugF52wi6oVpxq7heF8TcgJuGTkBjjLH4xNMBhacfMI5Jkam",
                            Username = "Adopter2"
                        },
                        new
                        {
                            Id = 16,
                            Email = "Adopter3@email.com",
                            Password = "$2a$11$6EEoXtxUnt4Y/kuNTF9X.OxNNUu/PzkY0Bof7eT0Mybjzv3HubOCG",
                            Username = "Adopter3"
                        },
                        new
                        {
                            Id = 17,
                            Email = "Adopter4@email.com",
                            Password = "$2a$11$c.k1oUXslMgb5PrphgKtnOkyjnpmrMhM8TBF0EAfbWNR1OoPPxQia",
                            Username = "Adopter4"
                        });
                });

            modelBuilder.Entity("ModelLayer.Entities.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRole");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 2,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 3,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 4,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 5,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 6,
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 6,
                            RoleId = 4
                        },
                        new
                        {
                            UserId = 7,
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 7,
                            RoleId = 5
                        },
                        new
                        {
                            UserId = 8,
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 8,
                            RoleId = 4
                        },
                        new
                        {
                            UserId = 8,
                            RoleId = 5
                        },
                        new
                        {
                            UserId = 9,
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 10,
                            RoleId = 4
                        },
                        new
                        {
                            UserId = 10,
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 11,
                            RoleId = 4
                        },
                        new
                        {
                            UserId = 11,
                            RoleId = 5
                        },
                        new
                        {
                            UserId = 12,
                            RoleId = 4
                        },
                        new
                        {
                            UserId = 12,
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 12,
                            RoleId = 5
                        },
                        new
                        {
                            UserId = 13,
                            RoleId = 4
                        },
                        new
                        {
                            UserId = 14,
                            RoleId = 5
                        },
                        new
                        {
                            UserId = 15,
                            RoleId = 5
                        },
                        new
                        {
                            UserId = 15,
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 16,
                            RoleId = 5
                        },
                        new
                        {
                            UserId = 16,
                            RoleId = 4
                        },
                        new
                        {
                            UserId = 17,
                            RoleId = 5
                        },
                        new
                        {
                            UserId = 17,
                            RoleId = 4
                        },
                        new
                        {
                            UserId = 17,
                            RoleId = 3
                        });
                });

            modelBuilder.Entity("ModelLayer.Entities.AdoptionRegistrationForm", b =>
                {
                    b.HasOne("ModelLayer.Entities.Pet", "Pet")
                        .WithOne("AdoptionRegistrationForm")
                        .HasForeignKey("ModelLayer.Entities.AdoptionRegistrationForm", "PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModelLayer.Entities.User", "User")
                        .WithMany("AdoptionRegistrationForms")
                        .HasForeignKey("UserId");

                    b.Navigation("Pet");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ModelLayer.Entities.Certification", b =>
                {
                    b.HasOne("ModelLayer.Entities.Pet", "Pet")
                        .WithOne("Certification")
                        .HasForeignKey("ModelLayer.Entities.Certification", "PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModelLayer.Entities.User", "ShelterStaff")
                        .WithMany()
                        .HasForeignKey("ShelterStaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ModelLayer.Entities.User", "User")
                        .WithMany("Certifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pet");

                    b.Navigation("ShelterStaff");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ModelLayer.Entities.Donation", b =>
                {
                    b.HasOne("ModelLayer.Entities.User", "User")
                        .WithMany("Donations")
                        .HasForeignKey("DonorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ModelLayer.Entities.Shelter", "Shelter")
                        .WithMany("Donations")
                        .HasForeignKey("ShelterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shelter");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ModelLayer.Entities.Event", b =>
                {
                    b.HasOne("ModelLayer.Entities.Shelter", "Shelter")
                        .WithMany("Events")
                        .HasForeignKey("ShelterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shelter");
                });

            modelBuilder.Entity("ModelLayer.Entities.FeedBack", b =>
                {
                    b.HasOne("ModelLayer.Entities.Post", "Post")
                        .WithMany("FeedBacks")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModelLayer.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ModelLayer.Entities.Notification", b =>
                {
                    b.HasOne("ModelLayer.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ModelLayer.Entities.Pet", b =>
                {
                    b.HasOne("ModelLayer.Entities.Shelter", "Shelter")
                        .WithMany("Pets")
                        .HasForeignKey("ShelterID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModelLayer.Entities.User", "User")
                        .WithMany("Pets")
                        .HasForeignKey("UserID");

                    b.Navigation("Shelter");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ModelLayer.Entities.Post", b =>
                {
                    b.HasOne("ModelLayer.Entities.Pet", "Pet")
                        .WithMany()
                        .HasForeignKey("PetId");

                    b.HasOne("ModelLayer.Entities.User", "User")
                        .WithMany("Posts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pet");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ModelLayer.Entities.Status", b =>
                {
                    b.HasOne("ModelLayer.Entities.Pet", "Pet")
                        .WithMany("Statuses")
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pet");
                });

            modelBuilder.Entity("ModelLayer.Entities.User", b =>
                {
                    b.HasOne("ModelLayer.Entities.Event", "Event")
                        .WithMany("Users")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ModelLayer.Entities.Shelter", "Shelter")
                        .WithMany("Users")
                        .HasForeignKey("ShelterId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Event");

                    b.Navigation("Shelter");
                });

            modelBuilder.Entity("ModelLayer.Entities.UserRole", b =>
                {
                    b.HasOne("Domain.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModelLayer.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("ModelLayer.Entities.Event", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("ModelLayer.Entities.Pet", b =>
                {
                    b.Navigation("AdoptionRegistrationForm");

                    b.Navigation("Certification");

                    b.Navigation("Statuses");
                });

            modelBuilder.Entity("ModelLayer.Entities.Post", b =>
                {
                    b.Navigation("FeedBacks");
                });

            modelBuilder.Entity("ModelLayer.Entities.Shelter", b =>
                {
                    b.Navigation("Donations");

                    b.Navigation("Events");

                    b.Navigation("Pets");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("ModelLayer.Entities.User", b =>
                {
                    b.Navigation("AdoptionRegistrationForms");

                    b.Navigation("Certifications");

                    b.Navigation("Donations");

                    b.Navigation("Notifications");

                    b.Navigation("Pets");

                    b.Navigation("Posts");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
