// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RepositoryLayer;

#nullable disable

namespace RepositoryLayer.Migrations
{
    [DbContext(typeof(PawFundContext))]
    [Migration("20240929160955_v3")]
    partial class v3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool?>("Status")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "ShelterStaff"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Donor"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Volunteer"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Adopter"
                        });
                });

            modelBuilder.Entity("ModelLayer.Entities.AdoptionRegistrationForm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AdopterId")
                        .HasColumnType("int");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("IdentityProof")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("IncomeAmount")
                        .HasColumnType("decimal(16, 4)");

                    b.Property<int>("PetId")
                        .HasColumnType("int");

                    b.Property<int>("ShelterStaffId")
                        .HasColumnType("int");

                    b.Property<bool?>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PetId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("AdoptionRegistrationForm");
                });

            modelBuilder.Entity("ModelLayer.Entities.Certification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Desciption")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PetId")
                        .HasColumnType("int");

                    b.Property<bool?>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PetId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Certification");
                });

            modelBuilder.Entity("ModelLayer.Entities.Donation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(16, 4)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DonorId")
                        .HasColumnType("int");

                    b.Property<int>("ShelterId")
                        .HasColumnType("int");

                    b.Property<bool?>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ShelterId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Donations");
                });

            modelBuilder.Entity("ModelLayer.Entities.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ShelterId")
                        .HasColumnType("int");

                    b.Property<bool?>("Status")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("ShelterId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("ModelLayer.Entities.EventUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<bool?>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("EventUser");
                });

            modelBuilder.Entity("ModelLayer.Entities.FeedBack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("PostId")
                        .HasColumnType("int");

                    b.Property<bool?>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.ToTable("FeedBacks");
                });

            modelBuilder.Entity("ModelLayer.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool?>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("ModelLayer.Entities.Pet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdoptionStatus")
                        .HasColumnType("longtext");

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Breed")
                        .HasColumnType("longtext");

                    b.Property<string>("Color")
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Gender")
                        .HasColumnType("longtext");

                    b.Property<string>("Image")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ShelterID")
                        .HasColumnType("int");

                    b.Property<string>("Size")
                        .HasColumnType("longtext");

                    b.Property<bool?>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("StatusId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ShelterID");

                    b.HasIndex("UserID");

                    b.ToTable("Pets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Pet",
                            ShelterID = 1,
                            Type = "Dog"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Pet",
                            ShelterID = 1,
                            Type = "Cat"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Pet",
                            ShelterID = 1,
                            Type = "Dog"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Pet",
                            ShelterID = 1,
                            Type = "Cat"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Pet",
                            ShelterID = 1,
                            Type = "Dog"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Pet",
                            ShelterID = 1,
                            Type = "Cat"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Pet",
                            ShelterID = 1,
                            Type = "Dog"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Pet",
                            ShelterID = 1,
                            Type = "Cat"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Pet",
                            ShelterID = 1,
                            Type = "Dog"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Pet",
                            ShelterID = 2,
                            Type = "Cat"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Pet",
                            ShelterID = 2,
                            Type = "Dog"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Pet",
                            ShelterID = 2,
                            Type = "Cat"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Pet",
                            ShelterID = 2,
                            Type = "Dog"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Pet",
                            ShelterID = 2,
                            Type = "Cat"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Pet",
                            ShelterID = 2,
                            Type = "Dog"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Pet",
                            ShelterID = 2,
                            Type = "Cat"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Pet",
                            ShelterID = 2,
                            Type = "Dog"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Pet",
                            ShelterID = 2,
                            Type = "Dog"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Pet",
                            ShelterID = 2,
                            Type = "Dog"
                        });
                });

            modelBuilder.Entity("ModelLayer.Entities.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PetId")
                        .HasColumnType("int");

                    b.Property<bool?>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Post");
                });

            modelBuilder.Entity("ModelLayer.Entities.Shelter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capaxity")
                        .HasColumnType("int");

                    b.Property<decimal?>("DonationAmount")
                        .HasColumnType("decimal(16, 4)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool?>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Website")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Shelters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capaxity = 20,
                            Email = "PetShelter1@email.com",
                            Location = "Tp. HCM",
                            Name = "Shelter1",
                            PhoneNumber = "1234567890"
                        },
                        new
                        {
                            Id = 2,
                            Capaxity = 20,
                            Email = "PetShelter2@email.com",
                            Location = "Ha Noi",
                            Name = "Shelter2",
                            PhoneNumber = "0987654321"
                        });
                });

            modelBuilder.Entity("ModelLayer.Entities.ShelterStaff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ShelterId")
                        .HasColumnType("int");

                    b.Property<bool?>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ShelterId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("ShelterStaffs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ShelterId = 1,
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            ShelterId = 1,
                            UserId = 3
                        },
                        new
                        {
                            Id = 3,
                            ShelterId = 2,
                            UserId = 4
                        },
                        new
                        {
                            Id = 4,
                            ShelterId = 2,
                            UserId = 5
                        });
                });

            modelBuilder.Entity("ModelLayer.Entities.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Disease")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PetId")
                        .HasColumnType("int");

                    b.Property<bool?>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Vaccine")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("PetId");

                    b.ToTable("Statuses");
                });

            modelBuilder.Entity("ModelLayer.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Image")
                        .HasColumnType("longtext");

                    b.Property<string>("Location")
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .HasColumnType("longtext");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int");

                    b.Property<bool?>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Token")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("TotalDonation")
                        .HasColumnType("decimal(16, 4)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "Admin@email.com",
                            Password = "$2a$11$lS5x/jebcVbdg63hxywkc.TpITtXdHZs4bgeOrqB9IbqB1VsSvdqK",
                            Username = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Email = "Admin@email.com",
                            Password = "$2a$11$fq.DHf8t4gpVXo/lVcKi2ehibkHELKmcZdVyfjklmN6kE33Y2CJRy",
                            Username = "Staff1"
                        },
                        new
                        {
                            Id = 3,
                            Email = "Admin@email.com",
                            Password = "$2a$11$9QZ4t9zfv7PEW.2r4VYrYOJNQM/rqHjjed.ghxlk7nZmSxi1jKqPq",
                            Username = "Staff2"
                        },
                        new
                        {
                            Id = 4,
                            Email = "Admin@email.com",
                            Password = "$2a$11$CTEf6oTmm7/kmIzRu2cw5u3Tzy9fR6XIgRLLsVFKhO87XyCdbf80S",
                            Username = "Staff3"
                        },
                        new
                        {
                            Id = 5,
                            Email = "Admin@email.com",
                            Password = "$2a$11$AzHIi09nvQc0tSdXP.LL4OpwQw3oHjl5MBvcR2w37cUpAogiMWdt6",
                            Username = "Staff4"
                        },
                        new
                        {
                            Id = 6,
                            Email = "Admin@email.com",
                            Password = "$2a$11$YbRQza94rGC.7gcenYVKnOJ9oF78BT2q.BPXg4vE3n2qd5WtIBNtO",
                            Username = "Donor1"
                        },
                        new
                        {
                            Id = 7,
                            Email = "Admin@email.com",
                            Password = "$2a$11$MVoq2sTN7DgOhJiZDq02Jub4ScPFPlIHUw5YPH8jhJOt0Bw1hLfG2",
                            Username = "Donor2"
                        },
                        new
                        {
                            Id = 8,
                            Email = "Admin@email.com",
                            Password = "$2a$11$08hohXJMVCu0KFzCEpLBrO/ECVsqfHR6Pe9DBYbCrPSX36ul8fXBO",
                            Username = "Donor3"
                        },
                        new
                        {
                            Id = 9,
                            Email = "Admin@email.com",
                            Password = "$2a$11$KcntOhgRuO.wui7CSNgDoePOF.PHeFfM8QmEWJU0A8xgsggovBCtK",
                            Username = "Donor4"
                        },
                        new
                        {
                            Id = 10,
                            Email = "Admin@email.com",
                            Password = "$2a$11$MgoyApHXCpPKhLzcC/vgeODLG9WlXIPm.xj1JtN.Fe3M4q1ntsn3O",
                            Username = "Volunteer1"
                        },
                        new
                        {
                            Id = 11,
                            Email = "Admin@email.com",
                            Password = "$2a$11$lAdTkd0bRpTJSG8ExgX0V.2BsBBcvN0w6UF68zImsL5OXTQxS2DAK",
                            Username = "Volunteer2"
                        },
                        new
                        {
                            Id = 12,
                            Email = "Admin@email.com",
                            Password = "$2a$11$TJOMWRbOFXg0SgL79.l.6elZVYlt4G6HyUtZNLwTF1Z6iNoklgxf.",
                            Username = "Volunteer3"
                        },
                        new
                        {
                            Id = 13,
                            Email = "Admin@email.com",
                            Password = "$2a$11$lyzsX2KbPsIR29.U2QgKG.iPVO8St4UywRVJkzcBuDYrvggxqRe0C",
                            Username = "Volunteer4"
                        },
                        new
                        {
                            Id = 14,
                            Email = "Admin@email.com",
                            Password = "$2a$11$GZxPvUwLCRzUis4RYrEFKuRBDDfrxTlweAsylaA3HZ7LbbXN/huIO",
                            Username = "Adopter1"
                        },
                        new
                        {
                            Id = 15,
                            Email = "Admin@email.com",
                            Password = "$2a$11$Q0c.W36JaicNzWP8qwdbRO/J0zvE1qt8MvsA0ak58CRyBhelLFZ2C",
                            Username = "Adopter2"
                        },
                        new
                        {
                            Id = 16,
                            Email = "Admin@email.com",
                            Password = "$2a$11$Z3Sna1g2ZVRBesixfBzssOltEFhjkYjJX46JhH2tHN8gpFsNHp.lW",
                            Username = "Adopter3"
                        },
                        new
                        {
                            Id = 17,
                            Email = "Admin@email.com",
                            Password = "$2a$11$Qa9/dXJ.UoKRLAzULVUWiunqUxfBTIniWkDTFpt4mu4skfzFcxUpG",
                            Username = "Adopter4"
                        });
                });

            modelBuilder.Entity("ModelLayer.Entities.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<bool?>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRole");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RoleId = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            RoleId = 2,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            RoleId = 2,
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            RoleId = 2,
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            RoleId = 2,
                            UserId = 5
                        },
                        new
                        {
                            Id = 6,
                            RoleId = 3,
                            UserId = 6
                        },
                        new
                        {
                            Id = 7,
                            RoleId = 3,
                            UserId = 7
                        },
                        new
                        {
                            Id = 8,
                            RoleId = 3,
                            UserId = 8
                        },
                        new
                        {
                            Id = 9,
                            RoleId = 3,
                            UserId = 9
                        },
                        new
                        {
                            Id = 10,
                            RoleId = 4,
                            UserId = 10
                        },
                        new
                        {
                            Id = 11,
                            RoleId = 4,
                            UserId = 11
                        },
                        new
                        {
                            Id = 12,
                            RoleId = 4,
                            UserId = 12
                        },
                        new
                        {
                            Id = 13,
                            RoleId = 4,
                            UserId = 13
                        },
                        new
                        {
                            Id = 14,
                            RoleId = 5,
                            UserId = 14
                        },
                        new
                        {
                            Id = 15,
                            RoleId = 5,
                            UserId = 15
                        },
                        new
                        {
                            Id = 16,
                            RoleId = 5,
                            UserId = 16
                        },
                        new
                        {
                            Id = 17,
                            RoleId = 5,
                            UserId = 17
                        });
                });

            modelBuilder.Entity("ModelLayer.Entities.AdoptionRegistrationForm", b =>
                {
                    b.HasOne("ModelLayer.Entities.Pet", "Pet")
                        .WithOne("AdoptionRegistrationForm")
                        .HasForeignKey("ModelLayer.Entities.AdoptionRegistrationForm", "PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModelLayer.Entities.User", "User")
                        .WithMany("AdoptionRegistrationForms")
                        .HasForeignKey("UserId");

                    b.Navigation("Pet");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ModelLayer.Entities.Certification", b =>
                {
                    b.HasOne("ModelLayer.Entities.Pet", "Pet")
                        .WithOne("Certification")
                        .HasForeignKey("ModelLayer.Entities.Certification", "PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModelLayer.Entities.User", "User")
                        .WithMany("Certifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Pet");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ModelLayer.Entities.Donation", b =>
                {
                    b.HasOne("ModelLayer.Entities.Shelter", "Shelter")
                        .WithOne("Donation")
                        .HasForeignKey("ModelLayer.Entities.Donation", "ShelterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModelLayer.Entities.User", "User")
                        .WithMany("Donations")
                        .HasForeignKey("UserId");

                    b.Navigation("Shelter");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ModelLayer.Entities.Event", b =>
                {
                    b.HasOne("ModelLayer.Entities.Shelter", "Shelter")
                        .WithMany("Events")
                        .HasForeignKey("ShelterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shelter");
                });

            modelBuilder.Entity("ModelLayer.Entities.EventUser", b =>
                {
                    b.HasOne("ModelLayer.Entities.Event", "Event")
                        .WithMany("EventUser")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModelLayer.Entities.User", "User")
                        .WithOne("EventUser")
                        .HasForeignKey("ModelLayer.Entities.EventUser", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ModelLayer.Entities.FeedBack", b =>
                {
                    b.HasOne("ModelLayer.Entities.Post", "Post")
                        .WithMany("FeedBacks")
                        .HasForeignKey("PostId");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("ModelLayer.Entities.Notification", b =>
                {
                    b.HasOne("ModelLayer.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ModelLayer.Entities.Pet", b =>
                {
                    b.HasOne("ModelLayer.Entities.Shelter", "Shelter")
                        .WithMany("Pets")
                        .HasForeignKey("ShelterID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModelLayer.Entities.User", "User")
                        .WithMany("Pets")
                        .HasForeignKey("UserID");

                    b.Navigation("Shelter");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ModelLayer.Entities.Post", b =>
                {
                    b.HasOne("ModelLayer.Entities.User", "User")
                        .WithMany("Posts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ModelLayer.Entities.ShelterStaff", b =>
                {
                    b.HasOne("ModelLayer.Entities.Shelter", "Shelter")
                        .WithMany("Staffs")
                        .HasForeignKey("ShelterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModelLayer.Entities.User", "Users")
                        .WithOne("ShelterStaff")
                        .HasForeignKey("ModelLayer.Entities.ShelterStaff", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shelter");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("ModelLayer.Entities.Status", b =>
                {
                    b.HasOne("ModelLayer.Entities.Pet", "Pet")
                        .WithMany("Statuses")
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pet");
                });

            modelBuilder.Entity("ModelLayer.Entities.User", b =>
                {
                    b.HasOne("Domain.Entities.Role", null)
                        .WithMany("Users")
                        .HasForeignKey("RoleId");
                });

            modelBuilder.Entity("ModelLayer.Entities.UserRole", b =>
                {
                    b.HasOne("Domain.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModelLayer.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("ModelLayer.Entities.Event", b =>
                {
                    b.Navigation("EventUser");
                });

            modelBuilder.Entity("ModelLayer.Entities.Pet", b =>
                {
                    b.Navigation("AdoptionRegistrationForm");

                    b.Navigation("Certification");

                    b.Navigation("Statuses");
                });

            modelBuilder.Entity("ModelLayer.Entities.Post", b =>
                {
                    b.Navigation("FeedBacks");
                });

            modelBuilder.Entity("ModelLayer.Entities.Shelter", b =>
                {
                    b.Navigation("Donation");

                    b.Navigation("Events");

                    b.Navigation("Pets");

                    b.Navigation("Staffs");
                });

            modelBuilder.Entity("ModelLayer.Entities.User", b =>
                {
                    b.Navigation("AdoptionRegistrationForms");

                    b.Navigation("Certifications");

                    b.Navigation("Donations");

                    b.Navigation("EventUser");

                    b.Navigation("Notifications");

                    b.Navigation("Pets");

                    b.Navigation("Posts");

                    b.Navigation("ShelterStaff");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
